import type { Metadata } from "next";

import { inter } from "@/lib/font";
import "./globals.css";
import AuthProvider from "@/context/AuthProvider";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Product and Stock Management",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased`}
      >
        <AuthProvider>
        <Toaster position="top-center" />
  
          {children}
          </AuthProvider>

      </body>
    </html>
  );
}
